workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: test jean1
    environment:
      groups:
        - firebase_config
        - code_signing
      vars:
        BUNDLE_ID: "com.mison.serviceuser"
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: jean-baptiste
          include: true
          source: true
    scripts:
      - name: Restore firebase_options.dart
        script: |
          echo "$FIREBASE_OPTIONS_B64" | base64 --decode > lib/firebase_options.dart
      - name: Set up keychain
        script: keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      - name: Add certificates to keychain
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Disable Swift Package Manager
        script: flutter config --no-enable-swift-package-manager
      - name: Increment build number
        script: |
          #!/usr/bin/env bash
          set -e
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID")
          cd ios
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - jeanbaptistedielinang@gmail.com
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Testers-Mison
